version: '3'
services:
  gretl:
    image: sogis/gretl:latest
    entrypoint: /bin/sh -c
    command: gretl
    environment:
      ORG_GRADLE_PROJECT_dbUriPub: "jdbc:postgresql://pub-db/pub"
      ORG_GRADLE_PROJECT_dbUserPub: postgres
      ORG_GRADLE_PROJECT_dbPwdPub: postgres
      ORG_GRADLE_PROJECT_gretlEnvironment: ${ORG_GRADLE_PROJECT_gretlEnvironment:-dev}
    depends_on:
      - pub-db
  pub-db:
    image: sogis/postgis:14-3.2
    environment:
      POSTGRES_DB: pub
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "54322:5432"